# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: forbid-new-submodules
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: no-commit-to-branch  # blocks main commits.  To bypass do git commit --allow-empty
  - id: pretty-format-json

# For more information about mypy, see https://github.com/pre-commit/mirrors-mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy
    exclude: ^(docs/|example-plugin/|tests/fixtures)

# No tests in this project, but this is a template for how we would add pytest
# - repo: local
#   hooks:
#   - id: pytest
#     name: Check pytest unit tests pass
#     entry: poetry run test
#     pass_filenames: false
#     language: system
#     types: [python]

# For more information about check-poetry, https://gitlab.com/smop/pre-commit-hooks/-/blob/master/.pre-commit-hooks.yaml
- repo: local
  hooks:
  - id: check-poetry
    name: Poetry check
    description: Validates the structure of the pyproject.toml file
    entry: poetry check
    language: system
    pass_filenames: false
    files: pyproject.toml

# For more information about YAPF, see https://github.com/google/yapf
- repo: https://github.com/google/yapf
  rev: v0.40.2  # Use the sha / tag you want to point at
  hooks:
  - id: yapf
    name: yapf
    description: A formatter for Python files.
    entry: yapf
    language: python
    types: [python]
